name: Build and Release

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Package to EXE (jpackage)
        run: |
          mkdir dist
          jpackage --input build/libs --name MinecraftClone --main-jar Minecraft-Clone-1.0.jar --type exe --dest dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/MinecraftClone.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}